title: <p align="center"> Linh Tran </p>

logo: "/images/image_6483441.JPG"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/linh-tran-thao/">LinkedIn</a> |
  <a href="https://github.com/tthaolinh">GitHub</a>
  <a href="linhthaotran0902@gmail.com">Email</a>
  </p>
  
  <p align="justify">
  I am pursuing a BS degree in Applied Data Science at Information Sciences and Technology, Pennsylvania State University.
  <b><b>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
